Version: 2002-09-22 ksh93n
Sourced from ast-open-history version 2002-09-22 and:
ea2d0e84b63aa34c63bab9926f426eabe31c861b7cf475fbb28f291dd5f17c50  INIT.2002-09-22.tgz

diff --git a/bin/mamprobe b/bin/mamprobe
--- a/bin/mamprobe
+++ b/bin/mamprobe
@@ -1,5 +1,5 @@
 # mamprobe - generate MAM cc probe info
-# this script written to make it through all sh variants
+# this script is written to make it through all sh variants
 # Glenn Fowler <gsf@research.att.com>
 
 case $-:$BASH_VERSION in
@@ -10,25 +10,29 @@ command=mamprobe
 
 # check the options
 
+opt=
+
 case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 0123)	USAGE=$'
 [-?
-@(#)$Id: mamprobe (AT&T Labs Research) 2002-02-02 $
+@(#)$Id: mamprobe (AT&T Labs Research) 2002-09-22 $
 ]
 [+NAME?mamprobe - generate MAM cc probe info]
 [+DESCRIPTION?\bmamprobe\b generates MAM (make abstract machine) \bcc\b(1)
-	probe information for use by \bmamake\b(1). The probed compiler is
-	\acc-path\a and the information is placed in \ainfo-path\a.
-	\ainfo-path\a is usually \b$INSTALLROOT/lib/probe/C/mam/\b\ahash\a,
-	where \ahash\a is a hash of \acc-path\a.]
+	probe information for use by \bmamake\b(1). \acc-path\a is the
+	absolute path of the probed compiler and \ainfo-file\a is where
+	the information is placed. \ainfo-file\a is usually
+	\b$INSTALLROOT/lib/probe/C/mam/\b\ahash\a, where \ahash\a is a hash
+	of \acc-path\a. Any \ainfo-file\a directories are created if needed.
+	If \ainfo-file\a is \b-\b then the probe information is written to
+	the standard output.]
 [+?\bmamprobe\b and \bmamake\b are used in the bootstrap phase of
 	\bpackage\b(1) installation before \bnmake\b(1) is built. The
-	probed variables are:]{
-		[+mam_cc_DLL?compile for a small dll]
-		[+mam_cc_DLLBIG?compile for a large dll]
+	probed variable names are the \bnmake\b(1) names with a \bmam_\b
+	prefix, \bCC\b converted to \bcc\b,  and \b.\b converted to \b_\b.
+	Additional variables are:]{
+		[+_hosttype_?the \bpackage\b(1) host type]
 		[+mam_cc_L?\b-L\b\adir\a supported]
-		[+mam_cc_SHELLMAGIC?a magic line to be placed at the top
-			of installed shell scripts]
 		[+STDCAT?command to execute for \bcat\b(1); prefixed by
 			\bexecrate\b(1) on \b.exe\b challenged systems]
 		[+STDCMP?command to execute for \bcmp\b(1); prefixed by
@@ -44,14 +48,17 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 		[+STDRM?command to execute for \brm\b(1); prefixed by
 			\bexecrate\b(1) on \b.exe\b challenged systems]
 }
+[d:debug?Enable probe script debug trace.]
 
-info-path cc-path
+info-file cc-path
 
 [+SEE ALSO?\bexecrate\b(1), \bpackage\b(1), \bmamake\b(1), \bnmake\b(1),
 	\bprobe\b(1)]
 '
 	while	getopts -a "$command" "$USAGE" OPT
-	do	:
+	do	case $OPT in
+		d)	opt=-d ;;
+		esac
 	done
 	shift `expr $OPTIND - 1`
 	;;
@@ -63,224 +70,129 @@ info-path cc-path
 		--)	shift
 			break
 			;;
+		-)	break
+			;;
+		-d)	opt=-d
+			;;
 		-*)	echo $command: $1: unknown option >&2
 			;;
 		*)	break
 			;;
 		esac
-		echo "Usage: $command info-path cc-path" >&2
-		exit 2
+		set ''
+		break
 	done
 	;;
 esac
 
 # check the args
 
-case $# in
-0|1)	echo "Usage: $command info-path cc-path" >&2; exit 2 ;;
-esac
 case $1 in
+-)	;;
 /*)	;;
-*)	echo "$command: $1: info-path must be absolute" >&2; exit 1 ;;
+*)	set '' ;;
+esac
+case $2 in
+/*)	;;
+*)	set '' ;;
+esac
+case $# in
+0|1)	echo "Usage: $command info-file cc-path" >&2; exit 2 ;;
 esac
 info=$1
 shift
 cc=$*
-src=.c
-obj=.o
-exe=.exe
+
+# find the make probe script
+
+ifs=$IFS
+IFS=:
+set $PATH
+IFS=$ifs
+script=lib/probe/C/make/probe
+while	:
+do	case $# in
+	0)	echo "$0: ../$script: probe script not found on PATH" >&2
+		exit 1
+		;;
+	esac
+	case $1 in
+	'')	continue ;;
+	esac
+	makeprobe=`echo $1 | sed 's,[^/]*$,'$script,`
+	if	test -x $makeprobe
+	then	break
+	fi
+	shift
+done
 
 # create the info dir if necessary
 
-i=X$info
-ifs=$IFS
-IFS=/
-set $i
-IFS=$ifs
-while	:
-do	i=$1
-	shift
-	case $i in
-	X)	break ;;
-	esac
-done
 case $info in
-//*)	path=/ ;;
-*)	path= ;;
+/*)	i=X$info
+	ifs=$IFS
+	IFS=/
+	set $i
+	IFS=$ifs
+	while	:
+	do	i=$1
+		shift
+		case $i in
+		X)	break ;;
+		esac
+	done
+	case $info in
+	//*)	path=/ ;;
+	*)	path= ;;
+	esac
+	while	:
+	do	case $# in
+		0|1)	break ;;
+		esac
+		comp=$1
+		shift
+		case $comp in
+		'')	continue ;;
+		esac
+		path=$path/$comp
+		if	test ! -d $path
+		then	mkdir $path || exit
+		fi
+	done
+	;;
 esac
-while	:
-do	case $# in
-	0|1)	break ;;
-	esac
-	comp=$1
-	shift
-	case $comp in
-	'')	continue ;;
-	esac
-	path=$path/$comp
-	if	test ! -d $path
-	then	mkdir $path || exit
-	fi
-done
 
 # generate info in a tmp file and rename when finished
 
-tmp=/tmp/mam$$
-trap "cd /; rm -rf $tmp" 0 1 2 3 15
-mkdir $tmp || exit
-cd $tmp || exit
-exec < /dev/null > info 2>/dev/null
+case $info in
+-)	;;
+*)	tmp=/tmp/mam$$
+	trap "exec >/dev/null; rm -f $tmp" 0 1 2 3 15
+	exec > $tmp
+	echo "probing C language processor $cc for mam information" >&2
+	;;
+esac
 
 echo "note generated by $0 for $cc"
 
-# nmake _hosttype_
+(
+	set '' $opt $cc
+	shift
+	. $makeprobe
 
-_hosttype_=`package || $SHELL -c package` # unixware.i386 ksh needs the alt!
-echo "setv _hosttype_ $_hosttype_"
-
-# mam_cc_DLL is the cc dll compilation option
-
-case $_hosttype_ in
-win32.*|cygwin.*|os2.*)
-	echo "setv mam_cc_DLL -D_BLD_DLL"
-	echo "setv mam_cc_DLLBIG -D_BLD_DLL"
-	;;
-*)	dll=
-	echo '#include <stdio.h>
-extern int i;
-int i = 1;
-extern int f(){return(i);} int main(){FILE* fp=stdin;return(f());}' > dll$src
-	if	$cc -c dll$src 2>e
-	then	e=`wc -l e`
-		s=`wc dll$obj`
-		for opt in -Kpic -KPIC -fpic -pic +z '-G 0' -D_DLL_BLD -Wc,exportall
-		do	rm -f dll$obj dll$exe
-			$cc $opt -c dll$src 2>e && test -f dll$obj || continue
-			$cc $opt -o dll$exe dll$obj && test -f dll$exe || {
-				rm -f dll$exe
-				$cc -o dll$exe dll$obj && test -f dll$exe && continue
-			}
-			case $opt in
-			*-D[abcdefghijklmnopqrstuvwxyz]*=*)
-				dll=$opt
-				break
-				;;
-			-Wc,exportall)
-				# get specific since sgi gets this far too
-				rm -f dll$exe dll.x
-				$cc -Wl,dll -o dll$exe dll$obj || continue
-				test -f dll$exe || continue
-				test -f dll.x || continue
-				dll="$opt -D_SHARE_EXT_VARS"
-				so=.x
-				sd=.dll
-				shared=-Wl,dll
-				probe_sd=
-				probe_shared=
-				lddynamic=-Bdynamic
-				ldstatic=-Bstatic
-				break
-				;;
-			esac
-			case `wc -l e` in
-			$e)	;;
-			*)	continue ;;
-			esac
-			case $opt in
-			???*)	ns=`wc dll$obj`
-				case $ns in
-				$s)	continue ;;
-				esac
-				m=`echo " $opt" | sed -e 's/^ [-+]//g' -e 's/./-& /g' -e 's/[-+] //g'`
-				rm -f dll$obj
-				if	$cc $m -c dll$src 2>e && test -f dll$obj
-				then	case `wc dll$obj` in
-					$ns)	continue ;;
-					esac
-				fi
-				dll=$opt
-				break
-				;;
-			*)	case `wc dll$obj` in
-				$s)	;;
-				*)	dll=$opt
-					break
-					;;
-				esac
-				;;
-			esac
-		done
-		case $dll in
-		?*)	echo "setv mam_cc_DLL $dll -D_BLD_DLL"
-			DLL=$dll
-			set x x -Kpic -KPIC -fpic -fPIC -pic -PIC +z +Z
-			while	:
-			do	shift
-				shift
-				case $# in
-				0|1)	break ;;
-				esac
-				case $dll in
-				$1)	rm -f dll$obj dll$exe
-					$cc $2 -c dll$src 2>e && test -f dll$obj || break
-					$cc $2 -o dll$exe dll$obj && test -f dll$exe || {
-						rm -f dll$exe
-						$cc -o dll$exe dll$obj && test -f dll$exe && break
-					}
-					DLL=$2
-					break
-					;;
-				esac
-			done
-			echo "setv mam_cc_DLLBIG $DLL -D_BLD_DLL"
-			;;
-		esac
-	fi
-	;;
-esac
-
-# mam_cc_L defined if cc -Ldir works
-
-case $_hosttype_ in
-win32.*|cygwin.*|os2.*)
-	echo "setv mam_cc_L 1"
-	;;
-*)	echo 'main(){return 0;}' > main$src
-	if	$cc -c main$src >/dev/null
-	then	if	$cc -L. main$obj -lc >/dev/null
-		then	case $dll in
-			'')	;;
-			*)	echo "setv mam_cc_L 1" ;;
-			esac
-		fi
-	fi
-	;;
-esac
-
-# mam_cc_SHELLMAGIC defined if installed shell scripts need magic
-
-echo 'exec 4<&0
-echo ok' > ok
-chmod +x ok
-case `(eval ./ok | /bin/sh) 2>/dev/null` in
-ok)	;;
-*)	echo '#!/bin/env sh
-exec 4<&0
-echo ok' > ok
-	chmod +x ok
-	case `(eval ./ok | /bin/sh) 2>/dev/null` in
-	ok)	echo 'setv mam_cc_SHELLMAGIC #!/bin/env sh'
-		;;
-	*)	for i in /emx/bin/bash.exe /emx/bin/sh.exe
-		do	if	test -x $i
-			then	echo 'setv mam_cc_SHELLMAGIC #!'$i
-				break
-			fi
-		done
-		;;
+	case " $CC_DIALECT " in
+	*" -L "*)	echo "CC.L = 1" ;;
 	esac
-	;;
-esac
+
+) | sed \
+	-e '/^CC\./!d' \
+	-e 's/^CC./setv mam_cc_/' \
+	-e 's/^\([^=.]*\)\./\1_/' \
+	-e 's/^\([^=.]*\)\./\1_/' \
+	-e 's/ =//' \
+	-e 's/\$("\([^"]*\)")/\1/g'
+
+echo 'setv _hosttype_ ${mam_cc_HOSTTYPE}'
 
 # STD* are standard commands/flags with possible execrate(1)
 
@@ -316,4 +228,11 @@ done
 
 # all done
 
-cp info $info
+case $info in
+-)	;;
+*)	exec >/dev/null
+	test -f $info && rm -f $info
+	cp $tmp $info
+	chmod -w $info
+	;;
+esac
diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -1,6 +1,6 @@
 USAGE_LICENSE="[-author?Glenn Fowler <gsf@research.att.com>][-copyright?Copyright (c) 1999-2002 AT&T Corp.][-license?http://www.research.att.com/sw/license/ast-open.html][--catalog?INIT]"
 # package - source and binary package control
-# this script written to make it through all sh variants
+# this script is written to make it through all sh variants
 # Glenn Fowler <gsf@research.att.com>
 
 case $-:$BASH_VERSION in
@@ -20,8 +20,8 @@ package_use='=$HOSTTYPE=$PACKAGEROOT=$INSTALLROOT=$EXECROOT=$CC='
 
 admin_db=admin.db
 admin_env=admin.env
-admin_ditto="ditto --delete --update --verbose"
-admin_ditto_skip="OFFICIAL|old|*.tmp"
+admin_ditto="ditto --checksum --delete --update --verbose"
+admin_ditto_skip="OFFICIAL|core|old|*.core|*.tmp|.nfs*"
 default_url=default.url
 
 all_types='*.*|sun4'		# all but sun4 match *.*
@@ -29,7 +29,7 @@ all_types='*.*|sun4'		# all but sun4 match *.*
 case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 0123)	USAGE=$'
 [-?
-@(#)$Id: package (AT&T Labs Research) 2002-06-28 $
+@(#)$Id: package (AT&T Labs Research) 2002-09-22 $
 ]'$USAGE_LICENSE$'
 [+NAME?package - source and binary package control]
 [+DESCRIPTION?The \bpackage\b command controls source and binary packages.
@@ -99,13 +99,13 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 				\"\bpackage\b\".]
 			[+[user@]]host?The host name and optionally user name
 				for \brcp\b(1) and \brsh\b(1) access.]
-			[+[server::]]PACKAGEROOT?The absolute remote package
-				root directory and optionally the server name
-				if the directory is on a different server than
-				the master package root directory. If
-				\blib/package/admin/'$admin_env$'\b exists
-				under this directory then it is sourced by
-				\bsh\b(1) before \aaction\a is done. If this
+			[+[remote::]]PACKAGEROOT?The absolute remote package
+				root directory and optionally the remote
+				protocol (rsh or ssh) if the directory is on
+				a different server than the master package
+				root directory. If \blib/package/admin/'$admin_env$'\b
+				exists under this directory then it is sourced
+				by \bsh\b(1) before \aaction\a is done. If this
 				field begins with \b-\b then the host is
 				ignored. If this field contains \b:\b then
 				\bditto\b(1) is used to sync the remote \bsrc\b
@@ -160,7 +160,8 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 		directory prefixes. Otherwise each architecture will be
 		installed in a separate \barch/\b\aHOSTTYPE\a subdirectory of
 		\adirectory\a. The \aarchitecture\a \b-\b names the current
-		architecture. \adirectory\a must be an existing directory.]
+		architecture. \adirectory\a must be an existing directory.
+		This action requires \bnmake\b.]
 	[+license\b [ \apackage\a ... ]]?List the source license(s) for
 		\apackage\a on the standard output. Note that individual
 		components in \apackage\a may contain additional or replacement
@@ -175,7 +176,7 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 		in the \b$INSTALLROOT\b directory tree viewpathed on top of
 		the \b$PACKAGEROOT\b directory tree. Leaf directory names
 		matching the \b|\b-separated shell pattern \b$MAKESKIP\b
-		are ignored.]
+		are ignored. The \bview\b action is done before making.]
 	[+read\b [ \apackage\a ... | \aarchive\a ... ]]?Read the named
 		package or archive(s). Must be run from the package root
 		directory. Archives are searched for in \b.\b and
@@ -241,6 +242,8 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 		and group are changed as necessary to match the checksum entry.
 		A warning is printed on the standard error for each mismatch.
 		Requires the \bast\b package \bcksum\b(1) command.]
+	[+view?Initialize the architecture specific viewpath hierarchy. The
+		\bmake\b action implicitly calls this action.]
 	[+write\b [\aformat\a]] \atype\a ... [ \apackage\a ...]]?Write a
 		package archive for \apackage\a. All work is done in the
 		\b$PACKAGEROOT/lib/package\b directory. \aformat\a-specific
@@ -436,13 +439,14 @@ tab="        "
 verbose=0
 DEBUG=
 PROTOROOT=-
+SHELLMAGIC=-
 
 while	:
 do	case $# in
 	0)	set host type ;;
 	esac
 	case $1 in
-	admin|contents|copyright|host|install|license|list|make|read|release|remove|results|test|update|use|verify|write|TEST)
+	admin|contents|copyright|host|install|license|list|make|read|release|remove|results|test|update|use|verify|view|write|TEST)
 		action=$1
 		shift
 		break
@@ -763,12 +767,13 @@ ${eL}${eO}"
 		   [user@]host
 			   The host name and optionally user name for rcp(1)
 			   and rsh(1) access.
-		   [server:]PACKAGEROOT
+		   [remote:]PACKAGEROOT
 			   The absolute remote package root directory and
-			   optionally the server name if the directory is on
-			   a different server than the master package root
-			   directory. If lib/package/admin/'$admin_env$' exists
-			   under this directory then it is sourced by sh(1)
+			   optionally the remote prorocol (rsh or ssh) if
+			   the directory is on a different server than the
+			   master package root directory. If
+			   lib/package/admin/'$admin_env$' exists under
+			   this directory then it is sourced by sh(1)
 			   before ACTION is done. If this field begins with -
 			   then the host is ignored. If this field contains
 			   : then ditto(1) is used to sync the remote src
@@ -822,7 +827,8 @@ ${eL}${eO}"
 		the \"arch/HOSTTYPE\" directory prefixes. Otherwise each
 		architecture will be installed in a separate \"arch/HOSTTYPE\"
 		subdirectory of DIR. The ARCHITECTURE - names the current
-		architecture. DIR must be an existing directory.
+		architecture. DIR must be an existing directory. This action
+		requires nmake.
 	license [ package ... ]
 		List the source license(s) for PACKAGE on the standard output.
 		Note that individual components in PACKAGE may contain
@@ -838,7 +844,7 @@ ${eL}${eO}"
 		in the \$INSTALLROOT directory tree viewpathed on top of
 		the \$PACKAGEROOT directory tree. Leaf directory names
 		matching the |-separated shell pattern \$MAKESKIP
-		are ignored.
+		are ignored. The view action is done before making.
 	read [ package ... | archive ... ]
 		Read the named package archive(s). Must be run from the
 		package root directory. Archives are searched for in .
@@ -899,6 +905,8 @@ ${eL}${eO}"
 		as necessary to match the checksum entry. A warning is printed
 		on the standard error for each mismatch. Requires the ast
 		package cksum(1) command.
+	view	Initialize the architecture specific viewpath hierarchy. The
+		make action implicitly calls this action.]
 	write [closure] [exp|lcl|pkg|rpm] [base|delta] [binary|source] PACKAGE
 		Write an archive for PACKAGE. The archive name is
 		lib/package/SAVE/PACKAGE.RELEASE[.VERSION][.HOSTTYPE].SUFFIX:
@@ -1064,6 +1072,23 @@ executable() # [!] command
 	case $1 in
 	'!')	test ! -x "$2" -a ! -x "$2.exe"; return ;;
 	*)	test -x "$1" -o -x "$1.exe"; return ;;
+	esac
+}
+
+# initialize SHELLMAGIC
+# tangible proof of cygwin's disdain for unix (well, this and execrate)
+
+shellmagic()
+{
+	case $SHELLMAGIC in
+	'')	;;
+	-)	if	test -f /emx/bin/sh.exe
+		then	SHELLMAGIC='#!/emx/bin/sh.exe'$nl
+		elif	test -f /bin/env.exe
+		then	SHELLMAGIC='#!/bin/env sh'$nl
+		else	SHELLMAGIC=
+		fi
+		;;
 	esac
 }
 
@@ -1283,8 +1308,8 @@ hostinfo() # attribute ...
 		esac
 		_hostinfo_="$_hostinfo_ $cpu"
 		;;
-	name)	name=`hostname || uname -n || cat /etc/whoami || echo local`
-		_hostinfo_="$_hostinfo_ $name"
+	name)	_name_=`hostname || uname -n || cat /etc/whoami || echo local`
+		_hostinfo_="$_hostinfo_ $_name_"
 		;;
 	rating)	for rating in `grep -i ^bogomips /proc/cpuinfo 2>/dev/null | sed -e 's,.*:[ 	]*,,' -e 's,\(...*\)\..*,\1,' -e 's,\(\..\).*,\1,'`
 		do	case $rating in
@@ -1803,7 +1828,8 @@ main()
 			68*)			rhs=m$rhs ;;
 			esac
 			case $rhs in
-			i[x23456789]86|*86pc)	rhs=i386 ;;
+			i[x23456789]86|i?[x23456789]86|*86pc)
+						rhs=i386 ;;
 			esac
 			case $rhs in
 			arm[abcdefghijklmnopqrstuvwxyz_][0123456789]*)
@@ -1811,6 +1837,17 @@ main()
 			hppa)			rhs=pa ;;
 			esac
 			case $lhs in
+			?*coff|?*dwarf|?*elf)
+				case $lhs in
+				?*coff)	x=coff ;;
+				?*dwarf)x=coff ;;
+				?*elf)	x=elf ;;
+				esac
+				lhs=`echo ${lhs}XXX | sed -e "s/${x}XXX//"`
+				;;
+			esac
+			case $lhs in
+			bsdi)			lhs=bsd ;;
 			hpux)			lhs=hp ;;
 			mvs)			rhs=390 ;;
 			esac
@@ -2040,6 +2077,41 @@ $PACKAGE_USE)
 	$show PACKAGEROOT=$PACKAGEROOT
 	$show export PACKAGEROOT
 	export PACKAGEROOT
+
+	# initialize the architecture environment
+
+	case $KEEP_HOSTTYPE in
+	0)	hostinfo type
+		HOSTTYPE=$_hostinfo_
+		;;
+	1)	_PACKAGE_HOSTTYPE_=$HOSTTYPE
+		export _PACKAGE_HOSTTYPE_
+		;;
+	esac
+	$show HOSTTYPE=$HOSTTYPE
+	$show export HOSTTYPE
+	export HOSTTYPE
+	INSTALLROOT=$PACKAGEROOT/arch/$HOSTTYPE
+	case $action in
+	admin|install|make|read|remove|test|verify|view|write)
+		;;
+	*)	if	test ! -d $INSTALLROOT
+		then	INSTALLROOT=$PACKAGEROOT
+		fi
+		;;
+	esac
+	$show INSTALLROOT=$INSTALLROOT
+	$show export INSTALLROOT
+	export INSTALLROOT
+
+	# HOSTTYPE specific package profile
+
+	if	test -r $INSTALLROOT/lib/package/profile
+	then	. $INSTALLROOT/lib/package/profile
+	fi
+
+	# check the basic package hierarchy
+
 	case $action in
 	use)	packageroot $PACKAGEROOT || {
 			echo "$command: $PACKAGEROOT: invalid package root directory" >&2
@@ -2067,45 +2139,59 @@ $PACKAGE_USE)
 			case `ls -t $INITROOT/$i.sh $PACKAGEROOT/bin/$i 2>/dev/null` in
 			"$INITROOT/$i.sh"*)
 				note update $PACKAGEROOT/bin/$i
-				$exec cp $INITROOT/$i.sh $PACKAGEROOT/bin/$i || exit
+				shellmagic
+				case $SHELLMAGIC in
+				'')	$exec cp $INITROOT/$i.sh $PACKAGEROOT/bin/$i || exit
+					;;
+				*)	case $exec in
+					'')	{
+						echo "$SHELLMAGIC"
+						cat $INITROOT/$i.sh
+						} > $PACKAGEROOT/bin/$i || exit
+						;;
+					*)	echo "{
+echo \"$SHELLMAGIC\"
+cat $INITROOT/$i.sh
+} > $PACKAGEROOT/bin/$i"
+						;;
+					esac
+					;;
+				esac
 				$exec chmod +x $PACKAGEROOT/bin/$i || exit
 				;;
 			esac
 		done
+		for i in arch arch/$HOSTTYPE
+		do	test -d $PACKAGEROOT/$i || $exec mkdir $PACKAGEROOT/$i || exit
+		done
+		for i in lib lib/probe lib/probe/C lib/probe/C/make
+		do	test -d $INSTALLROOT/$i || $exec mkdir $INSTALLROOT/$i || exit
+		done
+		i=$INSTALLROOT/lib/probe/C/make/probe
+		case `ls -t $INITROOT/C+probe $INITROOT/make.probe $i 2>/dev/null` in
+			*/make/probe*$INITROOT/*$INITROOT/*)
+				;;
+			*)	note update $i
+				shellmagic
+				case $exec in
+				'')	{
+					case $SHELLMAGIC in
+					?*)	echo "$SHELLMAGIC" ;;
+					esac
+					cat $INITROOT/C+probe $INITROOT/make.probe
+					} > $i || exit
+					;;
+				*)	echo "{
+echo $SHELLMAGIC
+cat $INITROOT/C+probe $INITROOT/make.probe
+} > $i"
+					;;
+				esac
+				$exec chmod +x $i || exit
+				;;
+			esac
 		;;
 	esac
-
-	# initialize the package environment
-
-	case $KEEP_HOSTTYPE in
-	0)	hostinfo type
-		HOSTTYPE=$_hostinfo_
-		;;
-	1)	_PACKAGE_HOSTTYPE_=$HOSTTYPE
-		export _PACKAGE_HOSTTYPE_
-		;;
-	esac
-	$show HOSTTYPE=$HOSTTYPE
-	$show export HOSTTYPE
-	export HOSTTYPE
-	INSTALLROOT=$PACKAGEROOT/arch/$HOSTTYPE
-	case $action in
-	admin|install|make|read|remove|test|verify|write)
-		;;
-	*)	if	test ! -d $INSTALLROOT
-		then	INSTALLROOT=$PACKAGEROOT
-		fi
-		;;
-	esac
-	$show INSTALLROOT=$INSTALLROOT
-	$show export INSTALLROOT
-	export INSTALLROOT
-
-	# HOSTTYPE specific package profile
-
-	if	test -r $INSTALLROOT/lib/package/profile
-	then	. $INSTALLROOT/lib/package/profile
-	fi
 
 	# check if $CC is a cross compiler
 
@@ -2877,7 +2963,7 @@ components() # [ package ]
 			esac
 			;;
 		*)	
-			if	view package src lib/package/$p.pkg
+			if	view - src lib/package/$p.pkg
 			then	p=$_view_
 				op=::
 				exec < $p
@@ -2908,6 +2994,10 @@ components() # [ package ]
 					done
 				done
 				exec < /dev/null
+			elif	test -d $PACKAGEROOT/src/cmd/$p -o -d $PACKAGEROOT/src/lib/$p
+			then	_components_="$_components_ $p"
+			else	echo "$command: $p: package or component not found" >&2
+				exit 1
 			fi
 			;;
 		esac
@@ -2920,7 +3010,7 @@ capture() # file command ...
 {
 	case $make:$noexec in
 	:)	case $action in
-		install|make)
+		install|make|view)
 			o=$action
 			;;
 		*)	case $package in
@@ -3094,6 +3184,7 @@ admin)	while	test ! -f $admin_db
 	case $admin_on in
 	'')	admin_on="*" ;;
 	esac
+	hostname=
 	hosts=
 	pids=
 	trap 'kill $pids >/dev/null 2>&1' 1 2 3 15
@@ -3102,7 +3193,8 @@ admin)	while	test ! -f $admin_db
 		''|'#'*);;
 		*=*)	eval "$type $host $root $date $time $make $test $write $junk"
 			;;
-		*)	case $host in
+		*)	remote=rsh
+			case $host in
 			*@*)	IFS=@
 				set '' $host
 				IFS=$ifs
@@ -3122,11 +3214,19 @@ admin)	while	test ! -f $admin_db
 				IFS=:
 				set '' $root
 				IFS=$ifs
-				sync=$2
-				case $sync in
-				'')	sync=ditto ;;
+				sync=$host
+				case $hostname in
+				'')	hostinfo name
+					hostname=$_hostinfo_
+					;;
 				esac
-				root=$3
+				shift
+				case $# in
+				0)	;;
+				1)	root=$1 ;;
+				2)	remote=$1 root=$2 ;;
+				*)	remote=$1 sync=$2 root=$3 ;;
+				esac
 				;;
 			*)	sync=
 				;;
@@ -3142,30 +3242,49 @@ admin)	while	test ! -f $admin_db
 			'')	echo package "$admin_args" $host
 				{
 				case $sync in
-				ditto)	for dir in $src
+				?*)	for dir in $src
 					do	case $MAKESKIP in
 						'')	expr="--expr=if(name=='$admin_ditto_skip')status=SKIP" ;;
 						*)	expr="--expr=if(name=='$admin_ditto_skip'||level==1&&name=='$MAKESKIP')status=SKIP" ;;
 						esac
-						test -d $PACKAGEROOT/src/$dir && $admin_ditto "$expr" $PACKAGEROOT/src/$dir $user$host:$root/src/$dir
+						test -d $PACKAGEROOT/src/$dir && $admin_ditto --remote=$remote "$expr" $PACKAGEROOT/src/$dir $user$sync:$root/src/$dir
 					done
 					;;
 				esac
-				rsh $user$host ". ./.profile && cd $root && { test -f lib/package/admin/$admin_env && . ./lib/package/admin/$admin_env || true; } && \${SHELL:-/bin/sh} -c 'bin/package $admin_args PACKAGEROOT=$root HOSTTYPE=$type'" &
+				case $admin_action in
+				ditto)	;;
+				*)	if	ping -c 1 -w 4 $host >/dev/null 2>&1
+					then	cmd=". ./.profile && cd $root && { test -f lib/package/admin/$admin_env && . ./lib/package/admin/$admin_env || true; } && touch .package.tim && \${SHELL:-/bin/sh} -c 'bin/package $admin_args PACKAGEROOT=$root HOSTTYPE=$type'"
+						case $sync in
+						?*)	case " $admin_args " in
+							*" write "*" binary "*)
+								cmd="$cmd && cd lib/package/tgz && rcp \`tw -e 'type==REG&&name!=\"*.tim\"&&mtime>\"../../../.package.tim\".mtime\` $hostname:lib/package/tgz"
+								;;
+							esac
+							;;
+						esac
+						$remote $user$host "$cmd"
+					else	echo "$command: $host: down" >&2
+					fi
+					;;
+				esac
 				} < /dev/null > $admin_log/$name 2>&1 &
 				pids="$pids $!"
 				;;
 			*)	case $sync in
-				ditto)	for dir in $src
+				?*)	for dir in $src
 					do	case $MAKESKIP in
-						'')	expr="--expr=if(name=='$admin_ditto_skip')status=SKIP" ;;
-						*)	expr="--expr=if(name=='$admin_ditto_skip'||level==1&&name=='$MAKESKIP')status=SKIP" ;;
+						'')	expr="\"--expr=if(name=='$admin_ditto_skip')status=SKIP\"" ;;
+						*)	expr="\"--expr=if(name=='$admin_ditto_skip'||level==1&&name=='$MAKESKIP')status=SKIP\"" ;;
 						esac
-						test -d $PACKAGEROOT/src/$dir && $admin_ditto --show "$expr" $PACKAGEROOT/src/$dir $user$host:$root/src/$dir
+						test -d $PACKAGEROOT/src/$dir && $exec $admin_ditto --show --remote=$remote "$expr" $PACKAGEROOT/src/$dir $user$sync:$root/src/$dir
 					done
 					;;
 				esac
-				$exec rsh $user$host ". ./.profile && cd $root && \${SHELL:-/bin/sh} -c 'bin/package $admin_args PACKAGEROOT=$root HOSTTYPE=$type' < /dev/null > $admin_log/$name 2>&1 &"
+				case $admin_action in
+				ditto)	;;
+				*)	$exec $remote $user$host ". ./.profile && cd $root && \${SHELL:-/bin/sh} -c 'bin/package $admin_args PACKAGEROOT=$root HOSTTYPE=$type' < /dev/null > $admin_log/$name 2>&1 &" ;;
+				esac
 				;;
 			esac
 		esac
@@ -3196,8 +3315,9 @@ admin)	while	test ! -f $admin_db
 					E=`eval date -E \`egrep '[ 	](start|done)[ 	][ 	]*at[ 	]' $admin_log/$2 | sed -e 's/.*[ 	][ 	]*at[ 	][ 	]*//' -e 's/[ 	][ 	]*in[ 	].*$//' -e 's/.*/"&"/'\``
 					M=$6 T=$7 W=$8
 					case $admin_action in
-					make)	M=`grep -c ']: \*\*\*.* code ' $admin_log/$2` ;;
-					test)	T=`grep -ci 'failed' $admin_log/$2` ;;
+					make|view)
+						M=`grep -c ']: \*\*\*.* code ' $admin_log/$2` ;;
+					test)	T=`grep -ci 'fail' $admin_log/$2` ;;
 					*)	W=`grep '^[abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz]*:' $admin_log/$2 | egrep -cv 'start at|done  at|output captured|warning:'` ;;
 					esac
 					case $1 in
@@ -3544,6 +3664,7 @@ install)cd $PACKAGEROOT
 					else	echo "$command: $MAKE: not found" >&2
 						exit 1
 					fi
+					makecheck=
 				fi
 				if	test "" != "$exec"
 				then	(
@@ -3622,7 +3743,8 @@ license)# all work in $PACKAGESRC/LICENSES
 	done
 	;;
 
-make)	cd $PACKAGEROOT
+make|view)
+	cd $PACKAGEROOT
 	case $package in
 	'')	lic="lib/package/*.lic"
 		;;
@@ -3715,17 +3837,19 @@ make)	cd $PACKAGEROOT
 		if	test -d $i
 		then	test -d $INSTALLROOT/$i || $exec mkdir $INSTALLROOT/$i || exit
 			make_recurse $i
-			for j in `cd $i; find . $o | sed -e 's,^\./,,' -e 's,/[^/]*$,,' | sort -u`
+			for j in `cd $i; find . $o 2>/dev/null | sed -e 's,^\./,,' -e 's,/[^/]*$,,' | sort -u`
 			do	case $j in
 				$k|$MAKESKIP) continue ;;
 				esac
-				test -d $INSTALLROOT/$i/$j || $exec mkdir -p $INSTALLROOT/$i/$j || exit
+				test -d $INSTALLROOT/$i/$j ||
+				$exec mkdir -p $INSTALLROOT/$i/$j || exit
 			done
 		fi
 	done
 	for i in $lic
 	do	test -f $i || continue
-		cmp -s $i $INSTALLROOT/$i || $exec cp $PACKAGEROOT/$i $INSTALLROOT/$i
+		cmp -s $i $INSTALLROOT/$i 2>/dev/null ||
+		$exec cp $PACKAGEROOT/$i $INSTALLROOT/$i
 	done
 	if	test ! -f $INSTALLROOT/bin/.paths
 	then	case $exec in
@@ -3744,11 +3868,12 @@ make)	cd $PACKAGEROOT
 	then	$make cd $INSTALLROOT/bin
 		for i in chmod chgrp cmp cp ln mv rm
 		do	if	test ! -x $OK/$i -a -x /bin/$i.exe
-			then	case $exec in
-				'')	echo 'execrate /bin/'$i' "$@"' > $OK/$i
+			then	shellmagic
+				case $exec in
+				'')	echo "$SHELLMAGIC"'execrate /bin/'$i' "$@"' > $OK/$i
 					chmod +x $OK/$i
 					;;
-				*)	$exec echo 'execrate /bin/'$i' "$@" >' $OK/$i
+				*)	$exec echo \'"$SHELLMAGIC"'execrate /bin/'$i' "$@"'\'' >' $OK/$i
 					$exec chmod +x $OK/$i
 					;;
 				esac
@@ -3757,6 +3882,9 @@ make)	cd $PACKAGEROOT
 		PATH=$INSTALLROOT/bin/$OK:$PATH
 		export PATH
 	fi
+	case $action in
+	view)	exit 0 ;;
+	esac
 
 	# all work under $INSTALLROOT/src
 
@@ -3869,7 +3997,7 @@ make)	cd $PACKAGEROOT
 			ksh nmake tee cp ln mv rm \
 			*ast*.dll *cmd*.dll *dll*.dll *shell*.dll
 		do	if	executable $i
-			then	cmp -s $i $OK/$i ||
+			then	cmp -s $i $OK/$i 2>/dev/null ||
 				$exec cp $i $OK/$i
 			fi
 		done
@@ -4360,7 +4488,7 @@ results)set '' $target
 		error*|fail*)
 			filter=err
 			;;
-		make|test|write)
+		make|test|view|write)
 			def=$1
 			;;
 		old)	suf=old
@@ -4426,11 +4554,11 @@ results)set '' $target
 			do	echo "$sep==> $j <=="
 				sep=$nl
 				case $filter in
-				err)	$exec egrep '\*\*\*|fail|FAIL|^TEST.* [1-9][0-9]* error' $j | sed -e '/^TEST.\//s,/[^ ]*/,,'
+				err)	$exec egrep -i '\*\*\*|FAIL|^TEST.* [1-9][0-9]* error' $j | sed -e '/^TEST.\//s,/[^ ]*/,,'
 					;;
 				cat)	$exec cat $j
 					;;
-				*)	$exec egrep '^TEST|FAIL|fail' $j
+				*)	$exec egrep -i '^TEST|FAIL' $j
 					;;
 				esac
 			done
