Version: 2013-05-24 ksh93v-
Sourced from:
53ca97d5b6e30fc73f728b3897310abf15b30b349ba492356bf455552fa7b735  ast-open.2013-04-22.tgz
118b2c8a4d651727fcd680289be69941d3045951bf9e3a4d45dcb42f0658f014  INIT.2013-05-24.tgz
1fe0f39fc1746c4331ec1a2c9db9239909c6a2ac739ab73eb17b0cf991f2672a  ast-ksh.2013-05-24.tgz

diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -81,7 +81,7 @@ all_types='*.*|sun4'		# all but sun4 match *.*
 case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
 0123)	USAGE=$'
 [-?
-@(#)$Id: package (AT&T Research) 2012-11-20 $
+@(#)$Id: package (AT&T Research) 2013-05-17 $
 ]'$USAGE_LICENSE$'
 [+NAME?package - source and binary package control]
 [+DESCRIPTION?The \bpackage\b command controls source and binary
@@ -282,7 +282,7 @@ case `(getopts '[-][123:xyz]' opt --xyz; echo 0$opt) 2>/dev/null` in
         [+results\b [ \bfailed\b ]] [ \bpath\b ]] [ \bold\b ]] [\bmake\b | \btest\b | \bwrite\b ]]?List
             results and interesting messages captured by the most recent
             \bmake\b (default), \btest\b or \bwrite\b action. \bold\b
-            specifies the previous results, if any (current and previous
+            specifies the previous results, if any (current and previous 9
             results are retained.) \b$HOME/.pkgresults\b, if it exists,
             must contain an \begrep\b(1) expression of result lines to be
             ignored. \bfailed\b lists failures only and \bpath\b lists the
@@ -1103,7 +1103,7 @@ ${bT}(5)${bD}Read all unread package archive(s):${bX}
 	results [ path ] [ old ] [ make | test ]
 		List results and interesting messages captured by the most
 		recent make (default), test or write action. old specifies the
-		previous results, if any (current and previous results are
+		previous results, if any (current and previous 9 results are
 		retained.) $HOME/.pkgresults, if it exists, must contain an
 		egrep(1) expression of result lines to be ignored. failed lists
 		failures only and path lists the results file path only.
@@ -5846,8 +5846,7 @@ cat $j $k
 	then	eval capture nmake $nmakeflags \$makeflags \$noexec install ksh93 $assign
 		case $make$noexec in
 		'')	if	executable ! $KSH
-			then	echo "$command: $action: errors making $KSH" >&2
-				exit 1
+			then	echo "$command: $action: warning: errors making $KSH" >&2
 			fi
 			;;
 		*)	make=echo
@@ -6545,7 +6544,7 @@ results)set '' $target
 			*:test:*/ksh*)	filter=rt ;;
 			esac
 			;;
-		old)	suf=old
+		old)	suf=$suf.*
 			;;
 		on)	case $# in
 			1)	echo $command: $action: $1: host pattern argument expected >&2
